"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[templates]
git_push_bookmark = '"bede/" ++ change_id.short()'

[remotes.origin]
auto-track-bookmarks = "glob:bede/*"

[signing]
behavior = "drop"
backend = "ssh"
key = "~/.ssh/id_ed25519_sk.pub"
backends.ssh.allowed-signers = "~/.config/git/allowed_signers"

[git]
sign-on-push = true
